In [10]:
#question 1
import numpy as np
a=np.array([[2,3,5],[4,5,8],[6,7,4]])
a


array([[2, 3, 5],
       [4, 5, 8],
       [6, 7, 4]])

In [11]:
l=a.tolist()
l

[[2, 3, 5], [4, 5, 8], [6, 7, 4]]

In [12]:
#question 2
   #second method:
M=a.trace()
M

11

In [13]:
     #first method
sum=0
X=a.shape
row=X[0]
col=X[1]
for i in range (row):
  sum=sum+a[i,i]
sum

11

In [16]:
#question 3
a=np.array([[2,3,5],[4,5,8],[6,7,4]])
X=4
print(a[X<a])



[5 5 8 6 7]


In [18]:
#question 4
A=np.array([[2,3],[4,5]])
B=np.array([[5,8],[6,7]])
C=A+B
C



array([[ 7, 11],
       [10, 12]])

In [21]:
v=np.array([[2,3,9],[4,4,5],[1,5,8]])

v



array([[2, 3, 9],
       [4, 4, 5],
       [1, 5, 8]])

In [23]:
x=v.shape
row=x[0]
for i in range (row):
    y=np.mean(v[i])
    print("the mean of row",i," =", y)


the mean of row 0  = 4.666666666666667
the mean of row 1  = 4.333333333333333
the mean of row 2  = 4.666666666666667
